config/routes.rb
Rails.application.routes.draw do
  root 'pets#index'
  resources :pets, except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w[dog cat dragon turtle rabbit snake]

  validates :name, :species, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new, status: 422
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit, status: 422
    end
  end

  def destroy
    @pet.destroy
    redirect_to root_path, status: :see_other
  end

  private
    def pet_params
      params.require(:pet).permit(:name, :species, :last_seen_at, :last_seen_address, :found_at, :found_address, :found)
    end

    def set_pet
      @pet = Pet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets1418</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for pet do |f| %>
  <%= f.input :name %>
  <%= f.input :species %>
  <%= f.input :last_seen_address %>
  <%= f.input :last_seen_at %>
  <%= f.input :found_address %>
  <%= f.input :found_at %>
  <%= f.input :found %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/pets/edit.html.erb
<div class="row">
  <div class="col-6 mx-auto">
    <h1>Edit pet info</h1>
    <%= render 'form', pet: @pet %>
  </div>
</div>

app/views/pets/index.html.erb
<h1>Welcome to Lost Pets 1418</h1>

<div class="mb-4">
  <%= link_to 'Found a pet? Add it here!', new_pet_path, class: "btn btn-primary" %>
</div>

<div class="row">
  <% @pets.each do |pet| %>
    <%= link_to pet_path(pet), class: "col-4 mb-2" do %>
      <div class="card ">
        <div class="card-body">
          <h3 class="card-title"><%= pet.name %></h3>
          <p>Last seen:</p>
          <p><%= pet.last_seen_address %></p>
          <p><%= pet.last_seen_at %></p>
          <%= link_to "EDIT", edit_pet_path(pet) %>
          <%= link_to "DELETE", pet_path(pet), data: {turbo_method: :delete, turbo_confirm: 'are you sure?'} %>
        </div>
      </div>
    
    <% end %>
  <% end %>
</div>

app/views/pets/new.html.erb
<div class="row">
  <div class="col-6 mx-auto">
    <h1>Report a missing pet</h1>
    <%= render 'form', pet: @pet %>
  </div>
</div>

app/views/pets/show.html.erb
<div class="row">
  <div class="col-6">
    <h1><%= @pet.name %></h1>
    <p><%= @pet.species %></p>
    <p><%= @pet.last_seen_address %></p>
    <p><%= @pet.last_seen_at %></p>
    <p><%= @pet.found_address %></p>
    <p><%= @pet.found_at %></p>
    <p><%= @pet.found %></p>

    <%= link_to "Back to index", root_path, class: "btn btn-warning" %>
  </div>
</div>